#!/usr/bin/env python

import sys

from stepper_widget.stepper_widget_module import StepperWidget
from rqt_gui.main import Main

plugin = 'stepper_widget'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
